# Generated by Django 2.0.6 on 2018-06-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guanzhuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='guanzhuinfo',
            name='guanzhuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haoyou.userInfo'),
        ),
    ]
