# Generated by Django 2.0.6 on 2018-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haoyou', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guanzhuinfo',
            old_name='guanzhuID',
            new_name='myselfID',
        ),
        migrations.AddField(
            model_name='guanzhuinfo',
            name='friendid',
            field=models.IntegerField(default=0, verbose_name='关注'),
        ),
        migrations.AddField(
            model_name='guanzhuinfo',
            name='report',
            field=models.IntegerField(default=0, verbose_name='举报'),
        ),
        migrations.AddField(
            model_name='guanzhuinfo',
            name='unfriendid',
            field=models.IntegerField(default=0, verbose_name='黑名单'),
        ),
    ]
