# Generated by Django 2.0.6 on 2018-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haoyou', '0002_auto_20180618_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanzhuinfo',
            name='friendid',
            field=models.IntegerField(default=0, null=True, verbose_name='关注'),
        ),
        migrations.AlterField(
            model_name='guanzhuinfo',
            name='report',
            field=models.IntegerField(default=0, null=True, verbose_name='举报'),
        ),
        migrations.AlterField(
            model_name='guanzhuinfo',
            name='unfriendid',
            field=models.IntegerField(default=0, null=True, verbose_name='黑名单'),
        ),
    ]
