# Generated by Django 2.0.6 on 2018-06-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haoyou', '0003_auto_20180618_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanzhuinfo',
            name='myselfID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='haoyou.userInfo'),
        ),
        migrations.AlterModelTable(
            name='guanzhuinfo',
            table='guanzhuInfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userInfo',
        ),
    ]
